using Masticore.Resources;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Masticore.Entity
{
    /// <summary>
    /// Class for tracking the instance of the resources underlying one instance of the software
    /// UniversalId should be generated by the system
    /// </summary>
    public class TenantEntity : ResourceEntityBase, IUniversal
    {
        /// <summary>
        /// Property for tracking a cross-system unique identifer
        /// This should be big enough to track:
        /// - User IDs in AAD
        /// - Tenant IDs in AAD
        /// - Directory IDs in Okta
        /// - User IDs in Okta
        /// - Container names in Azure Storage
        /// - Partition and row keys in Azure Storage tables
        /// - Docuemnt ID in CosmosDB
        /// - etc
        /// It's based on a GUID w/ dashes (AAD IDs format)
        /// </summary>
        [Display(Name = "Universal ID")]
        [StringLength(36)]
        public string UniversalId { get; set; }

        /// <summary>
        /// Display name for Humans
        /// </summary>
        [StringLength(128, MinimumLength = 3)]
        public string Name { get; set; }

        /// <summary>
        /// To many on Organization
        /// </summary>
        public ICollection<OrganizationEntity> Organizations { get; set; }

        /// <summary>
        /// Collection of token settings associated with the tenant.  While there can be many
        /// token settings there should only be 1 active setting at a time.
        /// </summary>
        public ICollection<TokenSettingsEntity> TokenSettings { get; set; }
    }
}
