<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\Code\Soundbite\Soundbite\Soundbite.Common\Soundbite.Common.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Models\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Soundbite.Common.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="shortid" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Masticore.Services\Masticore.Services.csproj" />
    <ProjectReference Include="..\Masticore\Masticore.csproj" />
  </ItemGroup>

</Project>
