<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Queues" Version="12.11.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.19" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Masticore\Masticore.csproj" />
  </ItemGroup>

</Project>
