//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soundbite.AzBot.MsTeams {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soundbite.AzBot.MsTeams.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///  &quot;body&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;TextBlock&quot;,
        ///      &quot;text&quot;: &quot;Looks like you haven&apos;t used Action Messaging Extension app in this team/chat. Please click **Continue** to add this app.&quot;,
        ///      &quot;wrap&quot;: true
        ///    }
        ///  ],
        ///  &quot;actions&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;Action.Submit&quot;,
        ///      &quot;title&quot;: &quot;Continue&quot;,
        ///      &quot;data&quot;: {
        ///        &quot;msteams&quot;: {
        ///          &quot;justInTimeInstall&quot;: true
        ///        }
        ///      }
        ///    }
        ///  ],
        ///  &quot;version&quot;: &quot;1.0&quot;
        ///}.
        /// </summary>
        internal static string JustInTimeBotInstallCard {
            get {
                return ResourceManager.GetString("JustInTimeBotInstallCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;actions&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;Action.Submit&quot;,
        ///            &quot;title&quot;: &quot;Play - Soundbite Title&quot;,
        ///            &quot;url&quot;: &quot;https://localhost:3000/organizations/13MSq7q03gSAbH4QUynWp/feed#sbplay=bw0fmpo81ousxq3zrqbxx&quot;
        ///        }
        ///    ],
        ///    &quot;$schema&quot;: &quot;http://adaptivecards.io/schemas/adaptive-card.json&quot;,
        ///    &quot;version&quot;: &quot;1.5&quot;
        ///}.
        /// </summary>
        internal static string TestCard {
            get {
                return ResourceManager.GetString("TestCard", resourceCulture);
            }
        }
    }
}
