using Masticore;
using Masticore.Entity;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Soundbite.Entity
{
    /// <summary>
    /// Recurring Sessions
    /// </summary>
    public class SeriesEntity : ResourceEntityBase
    {
        // ISeriesFields

        [Required]
        [StringLength(128, MinimumLength = 3)]
        [JsonProperty]
        public string Name { get; set; }
        [JsonProperty]
        public Recurrence Recurrence { get; set; }
        [JsonProperty]
        public string RecurrenceData { get; set; }

        // Relationships

        /// <summary>
        /// To one on Organization
        /// </summary>
        public int OrganizationId { get; set; }
        public virtual OrganizationEntity Organization { get; set; }

        /// <summary>
        /// ID of the session that acts as a template for building new sessions in the series.
        /// The session referenced by this template ID does NOT have its Series property set
        /// to this object because it would cause a circular reference.
        /// </summary>
        public int TemplateId { get; set; }

        /// <summary>
        /// Reference to the session that acts as a template for building new sessions in 
        /// </summary>        
        public virtual SessionEntity Template { get; set; }

        /// <summary>
        /// To many on Sessions generated by this series
        /// </summary>
        public ICollection<SessionEntity> Sessions { get; set; }
    }
}
