<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Configurations>Debug;Release;DebugWithCodeGen;DebugNoSecurity</Configurations>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Extensions\**" />
	  <EmbeddedResource Remove="Extensions\**" />
	  <None Remove="Extensions\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="10.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.19">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.19" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Masticore\Masticore.csproj" />
	</ItemGroup>
</Project>
