using Masticore.Exceptions;
using Masticore.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Masticore.Resources
{
    /// <summary>
    /// Static class full of extensions for domain interfaces
    /// NOTE: You must persist changes yourself
    /// </summary>
    public static class ResourceExtensions
    {
        /// <summary>
        /// Gets the display name for the given <see cref="IUserFields"/>
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public static string DisplayName(this IUserFields user)
        {
            if (user is null)
            {
                throw new ArgumentNullException(nameof(user));
            }

            // Regular users should have both
            if (!string.IsNullOrEmpty(user.GivenName) && !string.IsNullOrEmpty(user.FamilyName))
            {
                return $"{user.GivenName} {user.FamilyName}";
            }

            // Claims-only users have only given
            if (!string.IsNullOrEmpty(user.GivenName))
            {
                return user.GivenName;
            }

            // Every user has email
            return user.Email;
        }

        // To calculate the collission probability for these factors: https://zelark.github.io/nano-id-cc/

        /// <summary>
        /// The length of ID generated by <see cref="NewRoute()"/>
        /// </summary>
        public const int RouteLength = 21;

        /// <summary>
        /// The allowed characters in a route generated by <see cref="NewRoute()"/>
        /// </summary>
        public const string RouteAlphabet = "0123456789abcdefghijklmnopqrstuvwxyz";

        /// <summary>
        /// Generates an ID using upon the <see href="https://github.com/codeyu/nanoid-net">nanoid Nuget package</see> with length <see cref="RouteLength"/> and alphabet <see cref="RouteAlphabet"/>
        /// </summary>
        /// <remarks>
        /// This identifier is non-sequential, cryptographically secure, URI-safe, <see href="https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names">AzStorage container and blob name safe</see>
        /// </remarks>
        /// <returns></returns>
        public static string NewRoute()
        {
            return Nanoid.Nanoid.Generate(RouteAlphabet, RouteLength);
        }

        /// <summary>
        /// Generates a new <see cref="IResource.Route"/> for the given object if it doesn't already have one
        /// NOTE: You must persist changes yourself
        /// </summary>
        /// <param name="resource"></param>
        /// <returns>The UniversalId for the object, which may be pre-existing</returns>
        public static string NewRoute(this IResource resource)
        {
            if (resource is null)
            {
                throw new ArgumentNullException(nameof(resource));
            }

            if (string.IsNullOrEmpty(resource.Route))
            {
                resource.Route = NewRoute();
            }

            return resource.Route;
        }

        /// <summary>
        /// Generates a new UniversalId
        /// </summary>
        /// <returns></returns>
        public static string NewUniversalId()
        {
            return Guid.NewGuid().ToString("N");
        }

        /// <summary>
        /// Assigns a new <see cref="IUniversal.UniversalId"/> if one is not already set
        /// </summary>
        /// <param name="universal"></param>
        /// <returns></returns>
        public static string NewUniversalId(this IUniversal universal)
        {
            if (universal is null)
            {
                throw new ArgumentNullException(nameof(universal));
            }

            if (string.IsNullOrEmpty(universal.UniversalId))
            {
                universal.UniversalId = NewUniversalId();
            }

            return universal.UniversalId;
        }

        /// <summary>
        /// Sets the timestamp for <see cref="IRecord.UpdatedUtc"/> and optionally <see cref="IRecord.CreatedUtc"/> if empty for the given <see cref="IResource"/>
        /// NOTE: You must persist changes yourself
        /// </summary>
        /// <param name="resource">Returns the new UpdatedUtc for the object</param>
        /// <returns>Returns the new UpdatedUtc for the object</returns>
        public static DateTime Timestamp(this IRecord resource)
        {
            if (resource is null)
            {
                throw new ArgumentNullException(nameof(resource));
            }

            resource.UpdatedUtc = Time.UtcNow;

            if (resource.CreatedUtc == default)
            {
                resource.CreatedUtc = resource.UpdatedUtc;
            }

            return resource.UpdatedUtc;
        }

        /// <summary>
        /// Sets <see cref="IRecord.DeletedUtc"/> for the given <see cref="IResource"/> object.
        /// NOTE: You must do your own persistence
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Returns the ArchiveUtc for the object, which may be in the past</returns>
        public static DateTime SoftDelete(this IRecord model)
        {
            if (model is null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            if (!model.DeletedUtc.HasValue)
            {
                model.DeletedUtc = Time.UtcNow;
            }

            return model.DeletedUtc.Value;
        }

        /// <summary>
        /// If set, this clears <see cref="IRecord.DeletedUtc"/> for the given <see cref="IResource"/> object
        /// </summary>
        /// <param name="resource"></param>
        /// <returns>True if the object was restored; otherwise, false if they were already active</returns>
        public static bool Restore(this IRecord resource)
        {
            if (resource is null)
            {
                throw new ArgumentNullException(nameof(resource));
            }

            if (resource.DeletedUtc.HasValue)
            {
                resource.DeletedUtc = null;
                resource.Timestamp();
                return true;
            }

            return false;
        }

        /// <summary>
        /// Returns true if the given <see cref="IRecord"/> object has been soft deleted; otherwise, return true.
        /// WARNING: This CANNOT be used in the Where of a LINQ query because it's not a SQL function
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public static bool IsDeleted(this IRecord model)
        {
            if (model is null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            return model.DeletedUtc.HasValue;
        }

        /// <summary>
        /// Stamps the invite date for the given <see cref="IInviteLifecycle"/> object.
        /// WARNING: This will reset the invite if already accepted
        /// </summary>
        /// <param name="invite"></param>
        public static void Invite(this IInviteLifecycle invite)
        {
            if (!invite.InviteUtc.HasValue)
            {
                invite.InviteUtc = Time.UtcNow;
            }

            invite.InviteAcceptUtc = null;
        }

        /// <summary>
        /// Returns true if the given <see cref="IInviteLifecycle"/> is in an exccepted state; otherwise, false
        /// </summary>
        /// <param name="invite"></param>
        public static bool IsAccepted(this IInviteLifecycle invite)
        {
            return invite.InviteAcceptUtc.HasValue;
        }

        /// <summary>
        /// Stamps the <see cref="IInviteLifecycle.InviteAcceptUtc"/> value to now if it doesn't have a value
        /// </summary>
        /// <param name="invite"></param>
        /// <returns>True if the user had not yet accepted; otherwise, false</returns>
        public static bool Accept(this IInviteLifecycle invite)
        {
            if (!invite.InviteUtc.HasValue)
            {
                invite.InviteUtc = Time.UtcNow;
            }

            if (!invite.InviteAcceptUtc.HasValue)
            {
                invite.InviteAcceptUtc = Time.UtcNow;
                return true;
            }

            return false;
        }

        private static EmailAddressAttribute EmailValidator { get; } = new EmailAddressAttribute();

        /// <summary>
        /// Converts the given string to an email; or if it's null or empty returns null
        /// WARNING: With throw an ArgumentException if email is not a valid email
        /// </summary>
        /// <param name="email"></param>
        /// <param name="shouldThrowError"></param>
        /// <returns></returns>
        public static string ToEmail(this string email, bool shouldThrowError = true)
        {
            // We pass through null or empty as valid
            if (string.IsNullOrEmpty(email))
            {
                return null;
            }

            email = email.Trim().ToLower();

            if (EmailValidator.IsValid(email))
            {
                return email;
            }
            else
            {
                if (shouldThrowError)
                {
                    throw new ArgumentException("Email address is invalid");
                }
                else
                {
                    return null;
                }
            }
        }

        /// <summary>
        /// Returns true if the given string is an email; otherwise, return false
        /// NOTE: If it's null or empty, this returns false
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        public static bool IsEmail(this string email)
        {
            if (string.IsNullOrWhiteSpace(email))
            {
                return false;
            }

            return email.ToEmail(false) != null;
        }

        /// <summary>
        /// Throws a <see cref="NotFoundException"/> if the given object is null
        /// </summary>
        /// <typeparam name="TObj"></typeparam>
        /// <param name="obj"></param>
        /// <param name="message">Automatically generates if not given</param>
        public static TObj AssertFound<TObj>(this TObj obj, string message = null) where TObj : IResource
        {
            if (obj is null)
            {
                if (message is null)
                {
                    message = $"Could not find {typeof(TObj).Name}";
                }
                throw new NotFoundException(message);
            }
            return obj;
        }

        /// <summary>
        /// Throws a <see cref="NotFoundException"/> if the given collection is null
        /// </summary>
        /// <typeparam name="TObj"></typeparam>
        /// <param name="obj"></param>
        /// <param name="message"></param>
        /// <returns></returns>
        public static IEnumerable<TObj> AssertFound<TObj>(this IEnumerable<TObj> obj, string message = null) where TObj : IResource
        {
            if (obj is null)
            {
                if (message is null)
                {
                    message = $"Could not find {typeof(TObj).Name}";
                }
                throw new NotFoundException(message);
            }
            return obj;
        }

        /// <summary>
        /// Inspects the given object and will emit a <see cref="ResourceGoneException"/> if it is missing or soft-deleted
        /// </summary>
        /// <typeparam name="TObj"></typeparam>
        /// <param name="obj"></param>
        /// <param name="message"></param>
        /// <returns></returns>
        /// <exception cref="ResourceGoneException"></exception>
        public static TObj AssertNotGone<TObj>(this TObj obj, string message = null) where TObj : IResource
        {
            if (obj is null || obj.DeletedUtc != null)
            {
                if (message is null)
                {
                    message = $"{typeof(TObj).Name} existed, but is no longer inaccessible";
                }
                throw new ResourceGoneException(message);
            }
            return obj;
        }
    }
}
