<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Configurations>Debug;Release;DebugWithCodeGen;DebugNoSecurity</Configurations>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.19" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Masticore.Entity\Masticore.Entity.csproj" />
		<ProjectReference Include="..\Masticore\Masticore.csproj" />
	</ItemGroup>

</Project>
