using System;
using System.Collections.Generic;

namespace Masticore.Transcription.Interfaces
{
    /// <summary>
    /// Interface that defines the data present in a transcript file generated by Azure Speach to Text (ASTT).
    /// </summary>
    public interface ITranscriptAstt
    {
        TimeSpan Duration { get; set; }
        string Format { get; set; }
        Version Version { get; set; }
        DateTime Date { get; set; }
        TimeSpan ProcessingDuration { get; set; }
        IList<TranscriptionSection> Sections { get; set; }
        string State { get; set; }
        object ErrorDetails { get; set; }
    }
}