using System;

namespace Masticore.Transcription.Interfaces
{
    /// <summary>
    /// Interface that defines the data present in a transcript file generated by Azure Media 
    /// Services (AMS) transcription transform.
    /// </summary>
    public interface ITranscriptAms
    {
        TimeSpan Duration { get; set; }
        Version Version { get; set; }
        string SourceLanguage { get; set; }
        string[] Languages { get; set; }
        AmsTranscript[] Transcript { get; set; }
    }
}