<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Configurations>Debug;Release;DebugWithCodeGen;DebugNoSecurity</Configurations>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libphonenumber-csharp" Version="8.12.43" />
    <PackageReference Include="Twilio" Version="5.52.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Masticore\Masticore.csproj" />
  </ItemGroup>

</Project>
